// Top-level routing (§17.6). FROZEN — agents implement the referenced page
// components in their own folders; they do not edit this file.
//   /app/login                      builder login
//   /app                            dashboard (auth)
//   /app/forms/new                  new form builder (auth)
//   /app/forms/:id                  form builder (auth)
//   /app/forms/:id/submissions      submissions viewer (auth)
//   /:slug                          public form (no auth)
//   /                               -> /app
import { Navigate, Route, Routes } from 'react-router-dom';
import { RequireAuth } from './lib/auth';
import { LoginPage } from './builder/LoginPage';
import { DashboardPage } from './builder/DashboardPage';
import { FormBuilderPage } from './builder/FormBuilderPage';
import { SubmissionsPage } from './builder/SubmissionsPage';
import { PublicFormPage } from './public/PublicFormPage';
import { NotFoundPage } from './public/NotFoundPage';

export function App(): JSX.Element {
  return (
    <Routes>
      <Route path="/" element={<Navigate to="/app" replace />} />

      <Route path="/app/login" element={<LoginPage />} />
      <Route
        path="/app"
        element={
          <RequireAuth>
            <DashboardPage />
          </RequireAuth>
        }
      />
      <Route
        path="/app/forms/new"
        element={
          <RequireAuth>
            <FormBuilderPage />
          </RequireAuth>
        }
      />
      <Route
        path="/app/forms/:id"
        element={
          <RequireAuth>
            <FormBuilderPage />
          </RequireAuth>
        }
      />
      <Route
        path="/app/forms/:id/submissions"
        element={
          <RequireAuth>
            <SubmissionsPage />
          </RequireAuth>
        }
      />

      <Route path="/:slug" element={<PublicFormPage />} />
      <Route path="*" element={<NotFoundPage />} />
    </Routes>
  );
}
